CREATE TABLE "room-m8s_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "room-m8s_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "room-m8s_conversation" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"userAId" varchar(255) NOT NULL,
	"userBId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "room-m8s_like" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "room-m8s_like_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"likerId" varchar(255) NOT NULL,
	"likedId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "room-m8s_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "room-m8s_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversationId" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"senderId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "room-m8s_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "room-m8s_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "room-m8s_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "room-m8s_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "room-m8s_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "room-m8s_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "room-m8s_account" ADD CONSTRAINT "room-m8s_account_userId_room-m8s_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."room-m8s_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room-m8s_message" ADD CONSTRAINT "room-m8s_message_conversationId_room-m8s_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."room-m8s_conversation"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room-m8s_message" ADD CONSTRAINT "room-m8s_message_senderId_room-m8s_user_id_fk" FOREIGN KEY ("senderId") REFERENCES "public"."room-m8s_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room-m8s_post" ADD CONSTRAINT "room-m8s_post_createdById_room-m8s_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."room-m8s_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "room-m8s_session" ADD CONSTRAINT "room-m8s_session_userId_room-m8s_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."room-m8s_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "room-m8s_account" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_conversation_pair" ON "room-m8s_conversation" USING btree ("userAId","userBId");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_conversation_userA" ON "room-m8s_conversation" USING btree ("userAId");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_conversation_userB" ON "room-m8s_conversation" USING btree ("userBId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "room-m8s_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "room-m8s_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "room-m8s_session" USING btree ("userId");